### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ezraholm50** [ezraholm50/BerryCloud#10]
Please leave your feedback here, if you post it here, you agree that I can use Pic's vid's and your github username to add to the github Wiki page of BerryCloud for other users to see.

**Please do not:**
* Post issues, make a new issue if you have any bugs/problems
* Start discussions here, please visit our IRC freenode /techandme

**Please do:**
* State your build eg: RPI2/3, HDD/SDD capacity, other usb ports plugged in, class of the SDcard
* State if your using it locally or with a domain and how did you achieve that?
* State: improvements/requests

**Comment by jacremer** [comment]
RPi3 not reachable after first reboot. HDD of 3TB attached. 16GB class 10 SD card; fixed lan ip address (192.168.2.12)
Running the set-up via SSH went fine until first reboot. After the reboot the RPi3 wasnt reachable anymore  via SSH (SSH log file is attached).  In my (Windows) network i find a server MTK-DTV-Sink, model Ralink Wireless Linux Client. Anyone has a clue what could be the issue? Thanks in advance.
[Install_192.168.2.12_20160415.log.zip](https://github.com/ezraholm50/BerryCloud/files/221580/Install_192.168.2.12_20160415.log.zip)

**Comment by ezraholm50** [comment]
First off, is your 3TB drive externally powered? Logs don' show anything abnormal. Please connect the RPI3 to a monitor and see if you can login. If so please check if anything is wrong with SSH, you could try reinstalling it. Please report back with the outcome. (Another option would be to run the install again. Also did you use the RPI3 files and extracted them to PI_BOOT after deleting the content of PI_BOOT?)

**Comment by jacremer** [comment]
Yes 3TB is externally powered and files in PI_BOOT are deleted; files in RPI3 are copied to PI_BOOT.
When i put a monitor keyboard and mouse to it the attached screen is shown. When i type in sudo app-get openssh-client and enter no reaction of the system follows.
![wp_20160416_001](https://cloud.githubusercontent.com/assets/18489376/14579626/2fd37776-03b0-11e6-8bed-1a7590658206.jpg)

**Comment by ezraholm50** [comment]
Please use: apt-get remove openssh-server -y && apt-get  install openssh-server -y

Then try it again. Also please ping the ip of the RPI from another machine.

**Comment by jacremer** [comment]
Hi Esra ... let's first confess ... i'm a linux newbie :( ... next thanks for your help :)
I entered the command as described and pushed enter .... nothing happened except the screen output moved one line up. It looks like no commands are interpreted .. only pushing ctrl-alt-del forces a restart.
Can you please specify exactly what i need to type in?
Ping the ip doesn't help ... no ip is taken, device isn't active on the network.

**Comment by ezraholm50** [comment]
No problem, do you have a raspberry pi 2 aswell? During this week i can't
try and debug on my own machine. First option will be next weekend. I will
investigate the log file again tonight.

Op za 16 apr. 2016 16:30 schreef jacremer <notifications@github.com>:

> Hi Esra ... let's first confess ... i'm a linux newbie :( ... next thanks
> for your help :)
> I entered the command as described and pushed enter .... nothing happened
> except the screen output moved one line up. It looks like no commands are
> interpreted .. only pushing ctrl-alt-del forces a restart.
> Can you please specify exactly what i need to type in?
> Ping the ip doesn't help ... no ip is taken, device isn't active on the
> network.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-210826670>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
Yes i have a Pi2, my media player. You mean put the original PI_Boot back on the SD card and replace the PI3 with the PI2 and see what happens? Or shall i start all over again from scratch with the PI2?

**Comment by ezraholm50** [comment]
Best to do it from scratch to see if its rpi3 related. And also please
include the logs you did earlier. That could be useful.

Thanks

Op zo 17 apr. 2016 09:49 schreef jacremer <notifications@github.com>:

> Yes i have a Pi2, my media player. You mean put the original PI_Boot back
> on the SD card and replace the PI3 with the PI2 and see what happens? Or
> shall i start all over again from scratch with the PI2?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-210971713>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by cprinze** [comment]
maybe give it a try without using external hdd to figure out if it is a copy or partitioning problem

**Comment by ezraholm50** [comment]
@cprinze good one as it fails after the pre_setup.sh script. Will be a lot
easier to debug as soon as we know its the switch from sd to hd that causes
it.

Op zo 17 apr. 2016 12:27 schreef cprinze <notifications@github.com>:

> maybe give it a try without using external hdd to figure out if it is a
> copy or partitioning problem
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-210996513>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
I did a lot of tests today with PI2 and PI3. Most of the test (Pi2 and Pi3) ended with this screen.
![wp_20160417_006](https://cloud.githubusercontent.com/assets/18489376/14589681/6e73bb92-04e8-11e6-8978-5d93627ccf92.jpg)
with the system still reacting on removal of mouse and keyboard.
![wp_20160417_007](https://cloud.githubusercontent.com/assets/18489376/14589685/8e4fad90-04e8-11e6-9148-4aded4b4cbb4.jpg)
To my it looks like i got a bad/damaged SD card and i decided to format the SD card and start from scratch again. First on the Pi2 ... with no change in the result. So i decided to check whether my mediaplayer (OSMC) was still working at the Pi2 ... it was. So i put the Pi3_boot on the sd card and retry with the Pi3 ... i dont know why but the pre-set-up was running again ... resulting in this screen.
![wp_20160417_015](https://cloud.githubusercontent.com/assets/18489376/14589710/1a35c7cc-04e9-11e6-8d51-f958e6a43417.jpg)
At that moment i was very happy and hit the enter key with bad results :(
![wp_20160417_017](https://cloud.githubusercontent.com/assets/18489376/14589720/428166aa-04e9-11e6-973a-0b35e208ac4d.jpg)
![wp_20160417_018](https://cloud.githubusercontent.com/assets/18489376/14589721/46f9c75e-04e9-11e6-9507-18cfbde6518e.jpg)
I think the picture 015 at the end of the pre-setup shows the error. Now i will try to start from scratch again without hd.

**Comment by ezraholm50** [comment]
Yes please do. Indeed the kernel panic shows it. I had that aswell but when
i have it its after creating the sdcard and booting right away. As I said I
can test this weekend.. please post the outcome of the non hd install. And
also try a fresh sdcard, not the one you are using right now. Maybe backup
OSMC and use that one. You only need a 4 gb card.

Op zo 17 apr. 2016 22:15 schreef jacremer <notifications@github.com>:

> I did a lot of tests today with PI2 and PI3. Most of the test (Pi2 and
> Pi3) ended with this screen.
> [image: wp_20160417_006]
> <https://cloud.githubusercontent.com/assets/18489376/14589681/6e73bb92-04e8-11e6-8978-5d93627ccf92.jpg>
> with the system still reacting on removal of mouse and keyboard.
> [image: wp_20160417_007]
> <https://cloud.githubusercontent.com/assets/18489376/14589685/8e4fad90-04e8-11e6-9148-4aded4b4cbb4.jpg>
> To my it looks like i got a bad/damaged SD card and i decided to format
> the SD card and start from scratch again. First on the Pi2 ... with no
> change in the result. So i decided to check whether my mediaplayer (OSMC)
> was still working at the Pi2 ... it was. So i put the Pi3_boot on the sd
> card and retry with the Pi3 ... i dont know why but the pre-set-up was
> running again ... resulting in this screen.
> [image: wp_20160417_015]
> <https://cloud.githubusercontent.com/assets/18489376/14589710/1a35c7cc-04e9-11e6-8d51-f958e6a43417.jpg>
> At that moment i was very happy and hit the enter key with bad results :(
> [image: wp_20160417_017]
> <https://cloud.githubusercontent.com/assets/18489376/14589720/428166aa-04e9-11e6-973a-0b35e208ac4d.jpg>
> [image: wp_20160417_018]
> <https://cloud.githubusercontent.com/assets/18489376/14589721/46f9c75e-04e9-11e6-9507-18cfbde6518e.jpg>
> I think the picture 015 at the end of the pre-setup shows the error. Now i
> will try to start from scratch again without hd.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-211106873>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
preset-up for no HD 
![wp_20160417_020](https://cloud.githubusercontent.com/assets/18489376/14590225/e0849ec4-04f5-11e6-9e2e-4e040d10ccb7.jpg)
[Install_192.168.2.12_20160417.log.zip](https://github.com/ezraholm50/BerryCloud/files/222864/Install_192.168.2.12_20160417.log.zip)

was successfull .. below the log of the installation without HD.
![wp_20160417_019](https://cloud.githubusercontent.com/assets/18489376/14590223/d4375a6c-04f5-11e6-83a3-6b207d8a75f1.jpg)
Apache isn't running; webmin can be accessed.

**Comment by ezraholm50** [comment]
Thank you. Please run: service apache2 start

Then see if everything works. I will change the script asap. Now please run
the external_hd script.

Op zo 17 apr. 2016 23:50 schreef jacremer <notifications@github.com>:

> preset-up for no HD
> [image: wp_20160417_020]
> <https://cloud.githubusercontent.com/assets/18489376/14590225/e0849ec4-04f5-11e6-9e2e-4e040d10ccb7.jpg>
> Install_192.168.2.12_20160417.log.zip
> <https://github.com/ezraholm50/BerryCloud/files/222864/Install_192.168.2.12_20160417.log.zip>
>
> was successfull .. below the log of the installation without HD.
> [image: wp_20160417_019]
> <https://cloud.githubusercontent.com/assets/18489376/14590223/d4375a6c-04f5-11e6-83a3-6b207d8a75f1.jpg>
> Apache isn't running; webmin can be accessed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-211121085>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
Starting the apache2 service was not succesfull. see attached log.
[Install_192.168.2.12_20160418.log.zip](https://github.com/ezraholm50/BerryCloud/files/224191/Install_192.168.2.12_20160418.log.zip)

**Comment by ezraholm50** [comment]
Run the same line but add: sudo
So: sudo service apache2 start

If that doesnt work run: sudo apt-get install apache2

Please report back if it does install and it is not installes we need to
make a few adjustments to apache2 conf and the vhost files. This would
indicate that something in installing apache in the chroot went wrong.

Op ma 18 apr. 2016 18:17 schreef jacremer <notifications@github.com>:

> Starting the apache2 service was not succesfull. see attached log.
> Install_192.168.2.12_20160418.log.zip
> <https://github.com/ezraholm50/BerryCloud/files/224191/Install_192.168.2.12_20160418.log.zip>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-211452026>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
After installing apache2 was up and running. Accessing owncloud via owncloud desktop resulted into an error. Via browser connecting to owncloud (192.168.2.12/owncloud) was also not successful (not found). see attachment voor install log and screenprint of desktop error.
[Install_192.168.2.12_20160419.log.zip](https://github.com/ezraholm50/BerryCloud/files/226324/Install_192.168.2.12_20160419.log.zip)

**Comment by ezraholm50** [comment]
I see your dutch, Friday I'll add you to skype or you can join my ownCloud
server (chat app) and we can continue in dutch. The problem is in the image
itself I will fix it Friday. Also try to access ownCloud in your webbrowser
instead of the sync client should. Problem now is  that we don't have a
proper virtual host and not all the right mods are enabled.

Op di 19 apr. 2016 18:28 schreef jacremer <notifications@github.com>:

> After installing apache2 was up and running. Accessing owncloud via
> owncloud desktop resulted into an error. Via browser connecting to owncloud
> (192.168.2.12/owncloud) was also not successful (not found). see
> attachment voor install log and screenprint of desktop error.
> Install_192.168.2.12_20160419.log.zip
> <https://github.com/ezraholm50/BerryCloud/files/226324/Install_192.168.2.12_20160419.log.zip>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-212005062>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
I thought i can access owncloud in the browser via ip-address/owncloud but that returns an error.

**Comment by ezraholm50** [comment]
Normally you could but the issues I stated in my previous post makes
ownCloud not reachable. This is a small fix. I just have no access to a
laptop/desktop right now untill Friday.

Op wo 20 apr. 2016 00:11 schreef jacremer <notifications@github.com>:

> I thought i can access owncloud in the browser via ip-address/owncloud but
> that returns an error.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-212149938>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
Ok ... btw ... you can reach me on skype via jac.cremers. Please confirm you have read it so i can remove this message. Thanks.

**Comment by ezraholm50** [comment]
Got it talk to you soon

Op wo 20 apr. 2016 08:28 schreef jacremer <notifications@github.com>:

> Ok ... btw ... you can reach me on skype via jac.cremers. Please confirm
> you have read it so i can remove this message. Thanks.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-212279443>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by ezraholm50** [comment]
On my phone i can only search for your user name, there are 5 jaccremers...
my username is the same as here.

Op wo 20 apr. 2016 08:57 schreef Ezra Holm <ezraholm50@gmail.com>:

> Got it talk to you soon
>
> Op wo 20 apr. 2016 08:28 schreef jacremer <notifications@github.com>:
>
>> Ok ... btw ... you can reach me on skype via jac.cremers. Please confirm
>> you have read it so i can remove this message. Thanks.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-212279443>
>>
> --
>
> Met vriendelijke groet,
>
> E. Holm
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by ezraholm50** [comment]
@jacremer Please try out the newly uploaded image. Same download link. Uploading as we speak should be online in about 5 minutes.

**Comment by jacremer** [comment]
Hi Ezra, currently at work. Will try to do it tonight. Btw i send invite to your skype name. When searching for my name your omitted the "dot" in between :). Regards, Jac

**Comment by ezraholm50** [comment]
Good cause something went wrong uploading. Tonight I'll fix the download!

Op do 21 apr. 2016 08:33 schreef jacremer <notifications@github.com>:

> Hi Ezra, currently at work. Will try to do it tonight. Btw i send invite
> to your skype name. When searching for my name your omitted the "dot" in
> between :). Regards, Jac
>
>
>
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-212767223>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
Ok. Is the new build also for external hard disk? I'll try first with external hard disk.

**Comment by ezraholm50** [comment]
Yes it is, any news?

Op do 21 apr. 2016 17:07 schreef jacremer <notifications@github.com>:

> Ok. Is the new build also for external hard disk? I'll try first with
> external hard disk.
>
>
>
>
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-212963523>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
Hi Ezra. Could not find the download. When i reused the link i got an error. Just did a retry and it works (perhaps wrong browser; chrome versus firefox). I'll download when i'm at home (5pm) and run the install script. I'll post the results at 7pm (i guess) or Saturday morning. Thanks. Regards, Jac

**Comment by ezraholm50** [comment]
Thanks, I look forward to see the outcome. Meantime, I'll remove all the posts as this is a feedback post and not an issue. 

`Summary of this issue had something to do with the image, rechecked the image with a chroot and reinstalled some components. `

**Comment by ezraholm50** [comment]
@jacremer I can confirm that the image works as it should, succesfully installed. Only error is a repo error from webmin. Will be fixed soon

**Comment by jacremer** [comment]
@ezraholm50 We got panic again :(. See picture. Log of pre-setup attached.
[Install_192.168.2.12_20160422.log.zip](https://github.com/ezraholm50/BerryCloud/files/232059/Install_192.168.2.12_20160422.log.zip)
![wp_20160422_001](https://cloud.githubusercontent.com/assets/18489376/14745614/621ee200-08ac-11e6-9dd2-d9d93c77781b.jpg)

**Comment by ezraholm50** [comment]
Its defenetly sdcard related. I used a samsung evo sdcard today and with
BerryCloud it panic'd but with berryboot it works... another sdcard worked
right away with BerryCloud. please use a new sdcard.

Op vr 22 apr. 2016 17:05 schreef jacremer <notifications@github.com>:

> @ezraholm50 <https://github.com/ezraholm50> We got panic again :(. See
> picture. Log of pre-setup attached.
> Install_192.168.2.12_20160422.log.zip
> <https://github.com/ezraholm50/BerryCloud/files/232059/Install_192.168.2.12_20160422.log.zip>
> [image: wp_20160422_001]
> <https://cloud.githubusercontent.com/assets/18489376/14745614/621ee200-08ac-11e6-9dd2-d9d93c77781b.jpg>
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-213465999>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
Don't think it's SD card related. I bought 2 new Samsung EVO SDHC UHS-1 Cards and one of them i used for freshly install the new image. With this image it started up and reached the pre-set-up. Pre-set-up was executed and ended. Then it re-booted. As far as i know the (re-)boot is executed in three steps ... first from the board, then from the SD-Card and then from the drive (in this case the HD). Without the HD connected the boot process stops. With the HD connected the panic occurs. I guess the third boot step isn't correctly installed on the drive.

**Comment by ezraholm50** [comment]
How are you restoring the image to sdcard? Could you provide the logs if
the panic? And what is the outcome of the copy to hd part of the script.

Again I'd say it is an sd issue in combination with the hd. I ran the
install twice today without a hick up.

Op vr 22 apr. 2016 18:36 schreef jacremer <notifications@github.com>:

> Don't think it's SD card related. I bought 2 new Samsung EVO SDHC UHS-1
> Cards and one of them i used for freshly install the new image. With this
> image it started up and reached the pre-set-up. Pre-set-up was executed and
> ended. Then it re-booted. As far as i know the (re-)boot is executed in
> three steps ... first from the board, then from the SD-Card and then from
> the drive (in this case the HD). Without the HD connected the boot process
> stops. With the HD connected the panic occurs. I guess the third boot step
> isn't correctly installed on the drive.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-213501445>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
I use Win32 Disk Image v0.9.5 for writing the image to disk. I use the image BerryCloud_ownCloud_Ubuntu_Core_15.10_techandme.se.img, with size 907 MB (951.632.082 bytes).
When i run the Pi3 with the settings after the pre-set-up with hard disk powered off i get the first picture. When i put power on the HD the panic results.
![wp_20160422_003](https://cloud.githubusercontent.com/assets/18489376/14748977/31aa91bc-08bd-11e6-993f-8c1bb6f04b37.jpg)
The PI3 stops ... nothing happens then i put power on the Pi3
![wp_20160422_006](https://cloud.githubusercontent.com/assets/18489376/14748985/3b5d1040-08bd-11e6-956c-278023e70c29.jpg)
And immediately the panic is there.

**Comment by ezraholm50** [comment]
You use the newest image that I uploaded yesterday right? Also try to run
without hd and afterwards run the external_hd script with: sudo bash
external_hd.sh

Not sure what the file name is exactly do a: cd /var/scripts && ls

This will show the script

Op vr 22 apr. 2016 19:09 schreef jacremer <notifications@github.com>:

> I use Win32 Disk Image v0.9.5 for writing the image to disk. I use the
> image BerryCloud_ownCloud_Ubuntu_Core_15.10_techandme.se.img, with size 907
> MB (951.632.082 bytes).
> When i run the Pi3 with the settings after the pre-set-up with hard disk
> powered off i get the first picture. When i put power on the HD the panic
> results.
> [image: wp_20160422_003]
> <https://cloud.githubusercontent.com/assets/18489376/14748977/31aa91bc-08bd-11e6-993f-8c1bb6f04b37.jpg>
> The PI3 stops ... nothing happens then i put power on the Pi3
> [image: wp_20160422_006]
> <https://cloud.githubusercontent.com/assets/18489376/14748985/3b5d1040-08bd-11e6-956c-278023e70c29.jpg>
> And immediately the panic is there.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-213515510>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
Owncloud is running ... except the external_hd. Script isn't found. See attached log.
[Install_192.168.2.12_20160423.log.zip](https://github.com/ezraholm50/BerryCloud/files/232867/Install_192.168.2.12_20160423.log.zip)
You can try yourself. No passwords are changed. you can access via owncloud.putribulan.com ... when you can pass the certificate bullshit.

**Comment by ezraholm50** [comment]
Ok so you'll have to download the external_usb.sh and run it. Ill be home
in a bit I'll  post the command you should run soon. Also I'm testing the
upgrade to 16.04.

Op za 23 apr. 2016 10:52 schreef jacremer <notifications@github.com>:

> Owncloud is running ... except the external_hd. Script isn't found. See
> attached log.
> Install_192.168.2.12_20160423.log.zip
> <https://github.com/ezraholm50/BerryCloud/files/232867/Install_192.168.2.12_20160423.log.zip>
> You can try yourself. No passwords are changed. you can access via
> owncloud.putribulan.com ... when you can pass the certificate bullshit.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-213695075>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by ezraholm50** [comment]
ok run this:

`sudo cd /var/scripts && sudo wget https://raw.githubusercontent.com/ezraholm50/BerryCloud/master/external_usb.sh && sudo bash external_usb.sh`

**Comment by jacremer** [comment]
Hi Ezra. All went well untill i executed the command mentioned above. It took a very long time to execute and i fell a sleep. This morning the system was frozen again. Same 'panic' :(. Attached the log until the entered command was finalized.
[Install_192.168.2.12_20160423.log.zip](https://github.com/ezraholm50/BerryCloud/files/233311/Install_192.168.2.12_20160423.log.zip)

**Comment by ezraholm50** [comment]
Jac, that might just be an issue there, you could try with a HD below 2TB. I've read that it needs support indeed somewhere... please try it out and report back, anything below 2 TB works here.

**Comment by jacremer** [comment]
I tried with a 4GB USB stick... not big enough. I tried with a 64GB USB stick and yes it's working; means it starts up; i see a few fails. Unfortunateyly the site (/owncloud) isn;t working anymore (access denied); same counts for Webmin (:10000). Rebooting doesn't help. You know how to get the bootlog?
Why is external_usb moving the swap file and the boot files to the USB drive? i just want to use the hard drive for storing the data. Is any option available for moving the MySQL DB to the hard drive? Everything is stored in MySQL isn't it.

**Comment by ezraholm50** [comment]
It should remove a swapfile if present and create a swap partition when
using an external usb. Also the boot files stay on the sdcard the pi cant
boot without those on the sd.

The whole PI_ROOT partition is moved to the external usb so everything
should be on the usb.

Are you using the DynDns script or the Let'sencrypt script?

Op zo 24 apr. 2016 19:28 schreef jacremer <notifications@github.com>:

> I tried with a 4GB USB stick... not big enough. I tried with a 64GB USB
> stick and yes it's working; means it starts up; i see a few fails.
> Unfortunateyly the site (/owncloud) isn;t working anymore (access denied);
> same counts for Webmin (:10000). Rebooting doesn't help. You know how to
> get the bootlog?
> Why is external_usb moving the swap file and the boot files to the USB
> drive? i just want to use the hard drive for storing the data. Is any
> option available for moving the MySQL DB to the hard drive? Everything is
> stored in MySQL isn't it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-214004044>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
The other problem i have is with the certificate. I got a domain (owncloud.?.?) with the ip address of my router. Is the certificate valid for the local IP address of the Pi3? How do i achive this when i want to use the URL for getting access (via the router where 443 is routed to the Pi3)?

**Comment by jacremer** [comment]
Linux has no problem with large disks. It's the start-up of the RPi who has a problem. for me there's no need to swap file and the PI_Root to the USB drive. It could be the speed but most SD cards are fast enough nowadays.

**Comment by ezraholm50** [comment]
I need a bit more info, did you use the Let'sencrypt script to get the
certificate. Or is it from a retailer? Make sure port 443 is forwarded to
your pi.

Also the pi eats sdcards when it writes alot of data to the sd. Therefor i
choose to use the HD as an option.

Op zo 24 apr. 2016 19:37 schreef jacremer <notifications@github.com>:

> The other problem i have is with the certificate. I got a domain
> (owncloud.?.?) with the ip address of my router. Is the certificate valid
> for the local IP address of the Pi3? How do i achive this when i want to
> use the URL for getting access (via the router where 443 is routed to the
> Pi3)?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-214004632>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
Perhaps create a little bit bigger swap partition and move the PI_root also to this partition. So the RPi doesn't have to read the big stuff. The move to USB of 64GB wasn't successful also ... so something more is going wrong. It started up but nothing was running. You know how to activate/where to find the start-up log?

Router has 443 forwarded to RPi. URL owncloud.putribulan.com is pointing to my router (DNS CNAME). When i use the Let'sencrypt script and tell them to use this URL it fails. And i have no clue why. Unfortunately i have almost no time tonight for testing.

**Comment by ezraholm50** [comment]
That does not make any sense to have the root partition moved to the swap partition...
Swap partition will stay 2GB and The pi root partition will still take up every available byte.

Did you have 2 storage devices connected when you ran the external_usb.sh script?

the lets encrypt script fails because your server is blocking access to the rpi, disable your windows home server when you run the script, that should do it. then after that, you need to allow owncloud.domain.com to be accessed, make a rule in your server for that one to be allowed.

You could run the entire script and use SD and after a successful install let me SSH in to try to fix it.

**Comment by jacremer** [comment]
Make Swap partition a bit larger (4/8GB). I only connect 1 USB at the same time.
Ok i'll disable the home server and prepare everything. But don't know yet when i will have time .. perhaps on Kingsday evening.

**Comment by ezraholm50** [comment]
How would we benefit from a larger swap partition? Have you tested this? Cause my tests point out there's no need for a bigger then 2 GB swapfile / partition. Swappiness is set at 5 so only in worst case scenario's the swap will be used.

Not sure if Wednesday works for me but perhaps.. just let me know.

**Comment by jacremer** [comment]
Windows is/wasn't able to start from disks > 2TiB. Solution was to split large disks in multiple partitions with the primary partition < 2 TiB. You already created a 2 GiB partition for the swap file. The idea is to make this partition a bit large so it can also contain the PI_root directory).

**Comment by ezraholm50** [comment]
How do you need windows to boot it? You need the raspberry to boot it. You
should just create a third partition or rezise PI_ROOT to 1.7 TB or
something. No need to put the root in the swap partition that even cant be
done.

Or tomorrow i can provide a different external_usb.sh which fits your needs.

Op ma 25 apr. 2016 13:23 schreef jacremer <notifications@github.com>:

> Windows is/wasn't able to start from disks > 2TiB. Solution was to split
> large disks in multiple partitions with the primary partition < 2 TiB. You
> already created a 2 GiB partition for the swap file. The idea is to make
> this partition a bit large so it can also contain the PI_root directory).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-214272185>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
I mentioned windows just as example how the big disk issue was solved. Boot from the primary partition which is less than 2 TiB.
I expect the system will be up and running again in half an hour. Creating the certificate after shutting down WHS worked. But got error later on. No clue what is going wrong.
Which ports you need me to open for SSH?

**Comment by jacremer** [comment]
Site is up and running. I can reach webmin via internet. Still a problem with connecting to owncloud itself. I guess something is wrong with the router set-up.

**Comment by ezraholm50** [comment]
Ok so it runs on sd now right? What was the error?

We can also setup teamviewer or you could login to my webmin servers spreed
app and i can take over your desktop to also be able to check the router
settings and we can also voice chat in dutch.

You get a trusted domain error with owncloud i guess?

Op di 26 apr. 2016 08:54 schreef jacremer <notifications@github.com>:

> Site is up and running. I can reach webmin via internet. Still a problem
> with connecting to owncloud itself. I guess something is wrong with the
> router set-up.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-214637315>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
Yes running on sd, certificate not yet in place. Https://owncloud.putribulan.com/owncloud runs into a time out (The connection has timed out, no response from server).

Tonight i have to play cards again starting 19.15. i hope to be at home at 5. In between i can try to fix the router or set-up teamviewer or go to your webmin - spreed app.

**Comment by jacremer** [comment]
It's running fine now on SD. Certificate in place. Only problem to fix is now ... moving to external-usb.

**Comment by ezraholm50** [comment]
Great that wont be much of a problem. I suggest you create a backup of the
sdcard in case something goes wrong. You can create an account on my
owncloud https://waaromzomoeilijk.com then we can chat and i can use remote
desktop to fix it. Got time tonight?

Please tell me when you've read this so i can remove it.

Op wo 27 apr. 2016 22:31 schreef jacremer <notifications@github.com>:

> It's running fine now on SD. Certificate in place. Only problem to fix is
> now ... moving to external-usb.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ezraholm50/BerryCloud/issues/10#issuecomment-215218574>
>
-- 

Met vriendelijke groet,

E. Holm

**Comment by jacremer** [comment]
I'll be at home from 17.30 (perhaps 17.00) till 19.15. You know how to create a backup of the SD card? Which program to use? I got a spare SD card same size/type. Otherwise i will google.
Tried to create an account (registering) on the site mentioned above but it got an error message when the email should be send. I tried two email addresses ...jac.cremers@live.nl and jac.cremers@outlook.com (not preferred). You know what went wrong?
